services:
  - type: web
    name: spanish-wine-camps-api
    env: node
    plan: free
    buildCommand: "npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: APP_KEYS
        sync: false
      - key: API_TOKEN_SALT
        sync: false
      - key: ADMIN_JWT_SECRET
        sync: false
      - key: TRANSFER_TOKEN_SALT
        sync: false
